/*
Glean Client API - Platform Preview

# Introduction These are all the APIs used by Glean to implement the Glean client. These are available as platform preview for implementing a custom client to the Glean system.  # Usage guidelines A subset of these endpoints are also in the developer ready section, which is available for public use. The rest of the endpoints are subject to prior agreement with Glean before usage. Please contact support@glean.com if you would like to use an API that is not currently available in the developer ready section. 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gleanclientsdk

import (
	"encoding/json"
)

// checks if the EditDocumentCollectionsRequestAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditDocumentCollectionsRequestAllOf{}

// EditDocumentCollectionsRequestAllOf struct for EditDocumentCollectionsRequestAllOf
type EditDocumentCollectionsRequestAllOf struct {
	// The document ID of the item being added to or removed from collections if it's a Glean-indexed document.
	DocumentId *string `json:"documentId,omitempty"`
	// The url of the item being added to or removed from collections.
	Url *string `json:"url,omitempty"`
	// Custom title of the document if adding a non-indexed URL.
	Name *string `json:"name,omitempty"`
	// The description of this CollectionItem.
	Description *string `json:"description,omitempty"`
}

// NewEditDocumentCollectionsRequestAllOf instantiates a new EditDocumentCollectionsRequestAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditDocumentCollectionsRequestAllOf() *EditDocumentCollectionsRequestAllOf {
	this := EditDocumentCollectionsRequestAllOf{}
	return &this
}

// NewEditDocumentCollectionsRequestAllOfWithDefaults instantiates a new EditDocumentCollectionsRequestAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditDocumentCollectionsRequestAllOfWithDefaults() *EditDocumentCollectionsRequestAllOf {
	this := EditDocumentCollectionsRequestAllOf{}
	return &this
}

// GetDocumentId returns the DocumentId field value if set, zero value otherwise.
func (o *EditDocumentCollectionsRequestAllOf) GetDocumentId() string {
	if o == nil || IsNil(o.DocumentId) {
		var ret string
		return ret
	}
	return *o.DocumentId
}

// GetDocumentIdOk returns a tuple with the DocumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditDocumentCollectionsRequestAllOf) GetDocumentIdOk() (*string, bool) {
	if o == nil || IsNil(o.DocumentId) {
		return nil, false
	}
	return o.DocumentId, true
}

// HasDocumentId returns a boolean if a field has been set.
func (o *EditDocumentCollectionsRequestAllOf) HasDocumentId() bool {
	if o != nil && !IsNil(o.DocumentId) {
		return true
	}

	return false
}

// SetDocumentId gets a reference to the given string and assigns it to the DocumentId field.
func (o *EditDocumentCollectionsRequestAllOf) SetDocumentId(v string) {
	o.DocumentId = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *EditDocumentCollectionsRequestAllOf) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditDocumentCollectionsRequestAllOf) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *EditDocumentCollectionsRequestAllOf) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *EditDocumentCollectionsRequestAllOf) SetUrl(v string) {
	o.Url = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EditDocumentCollectionsRequestAllOf) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditDocumentCollectionsRequestAllOf) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EditDocumentCollectionsRequestAllOf) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EditDocumentCollectionsRequestAllOf) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EditDocumentCollectionsRequestAllOf) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditDocumentCollectionsRequestAllOf) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EditDocumentCollectionsRequestAllOf) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EditDocumentCollectionsRequestAllOf) SetDescription(v string) {
	o.Description = &v
}

func (o EditDocumentCollectionsRequestAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditDocumentCollectionsRequestAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DocumentId) {
		toSerialize["documentId"] = o.DocumentId
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableEditDocumentCollectionsRequestAllOf struct {
	value *EditDocumentCollectionsRequestAllOf
	isSet bool
}

func (v NullableEditDocumentCollectionsRequestAllOf) Get() *EditDocumentCollectionsRequestAllOf {
	return v.value
}

func (v *NullableEditDocumentCollectionsRequestAllOf) Set(val *EditDocumentCollectionsRequestAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableEditDocumentCollectionsRequestAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableEditDocumentCollectionsRequestAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditDocumentCollectionsRequestAllOf(val *EditDocumentCollectionsRequestAllOf) *NullableEditDocumentCollectionsRequestAllOf {
	return &NullableEditDocumentCollectionsRequestAllOf{value: val, isSet: true}
}

func (v NullableEditDocumentCollectionsRequestAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditDocumentCollectionsRequestAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


