/*
Glean Client API - Platform Preview

# Introduction These are all the APIs used by Glean to implement the Glean client. These are available as platform preview for implementing a custom client to the Glean system.  # Usage guidelines A subset of these endpoints are also in the developer ready section, which is available for public use. The rest of the endpoints are subject to prior agreement with Glean before usage. Please contact support@glean.com if you would like to use an API that is not currently available in the developer ready section. 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gleanclientsdk

import (
	"encoding/json"
)

// checks if the GetAnnouncementRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAnnouncementRequest{}

// GetAnnouncementRequest struct for GetAnnouncementRequest
type GetAnnouncementRequest struct {
	// The id of the announcement to be retrieved.
	Id int32 `json:"id"`
}

// NewGetAnnouncementRequest instantiates a new GetAnnouncementRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAnnouncementRequest(id int32) *GetAnnouncementRequest {
	this := GetAnnouncementRequest{}
	this.Id = id
	return &this
}

// NewGetAnnouncementRequestWithDefaults instantiates a new GetAnnouncementRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAnnouncementRequestWithDefaults() *GetAnnouncementRequest {
	this := GetAnnouncementRequest{}
	return &this
}

// GetId returns the Id field value
func (o *GetAnnouncementRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetAnnouncementRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetAnnouncementRequest) SetId(v int32) {
	o.Id = v
}

func (o GetAnnouncementRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAnnouncementRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableGetAnnouncementRequest struct {
	value *GetAnnouncementRequest
	isSet bool
}

func (v NullableGetAnnouncementRequest) Get() *GetAnnouncementRequest {
	return v.value
}

func (v *NullableGetAnnouncementRequest) Set(val *GetAnnouncementRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAnnouncementRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAnnouncementRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAnnouncementRequest(val *GetAnnouncementRequest) *NullableGetAnnouncementRequest {
	return &NullableGetAnnouncementRequest{value: val, isSet: true}
}

func (v NullableGetAnnouncementRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAnnouncementRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


