/*
Glean Client API - Platform Preview

# Introduction These are all the APIs used by Glean to implement the Glean client. These are available as platform preview for implementing a custom client to the Glean system.  # Usage guidelines A subset of these endpoints are also in the developer ready section, which is available for public use. The rest of the endpoints are subject to prior agreement with Glean before usage. Please contact support@glean.com if you would like to use an API that is not currently available in the developer ready section. 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gleanclientsdk

import (
	"encoding/json"
)

// checks if the GetExternalDocumentsProxyRequestQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetExternalDocumentsProxyRequestQuery{}

// GetExternalDocumentsProxyRequestQuery struct for GetExternalDocumentsProxyRequestQuery
type GetExternalDocumentsProxyRequestQuery struct {
	// Email address of the owner of the document
	Owner string `json:"owner"`
	// Type of documents to retrieve
	RequestType string `json:"requestType"`
}

// NewGetExternalDocumentsProxyRequestQuery instantiates a new GetExternalDocumentsProxyRequestQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetExternalDocumentsProxyRequestQuery(owner string, requestType string) *GetExternalDocumentsProxyRequestQuery {
	this := GetExternalDocumentsProxyRequestQuery{}
	this.Owner = owner
	this.RequestType = requestType
	return &this
}

// NewGetExternalDocumentsProxyRequestQueryWithDefaults instantiates a new GetExternalDocumentsProxyRequestQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetExternalDocumentsProxyRequestQueryWithDefaults() *GetExternalDocumentsProxyRequestQuery {
	this := GetExternalDocumentsProxyRequestQuery{}
	return &this
}

// GetOwner returns the Owner field value
func (o *GetExternalDocumentsProxyRequestQuery) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *GetExternalDocumentsProxyRequestQuery) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *GetExternalDocumentsProxyRequestQuery) SetOwner(v string) {
	o.Owner = v
}

// GetRequestType returns the RequestType field value
func (o *GetExternalDocumentsProxyRequestQuery) GetRequestType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestType
}

// GetRequestTypeOk returns a tuple with the RequestType field value
// and a boolean to check if the value has been set.
func (o *GetExternalDocumentsProxyRequestQuery) GetRequestTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestType, true
}

// SetRequestType sets field value
func (o *GetExternalDocumentsProxyRequestQuery) SetRequestType(v string) {
	o.RequestType = v
}

func (o GetExternalDocumentsProxyRequestQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetExternalDocumentsProxyRequestQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["owner"] = o.Owner
	toSerialize["requestType"] = o.RequestType
	return toSerialize, nil
}

type NullableGetExternalDocumentsProxyRequestQuery struct {
	value *GetExternalDocumentsProxyRequestQuery
	isSet bool
}

func (v NullableGetExternalDocumentsProxyRequestQuery) Get() *GetExternalDocumentsProxyRequestQuery {
	return v.value
}

func (v *NullableGetExternalDocumentsProxyRequestQuery) Set(val *GetExternalDocumentsProxyRequestQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableGetExternalDocumentsProxyRequestQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableGetExternalDocumentsProxyRequestQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetExternalDocumentsProxyRequestQuery(val *GetExternalDocumentsProxyRequestQuery) *NullableGetExternalDocumentsProxyRequestQuery {
	return &NullableGetExternalDocumentsProxyRequestQuery{value: val, isSet: true}
}

func (v NullableGetExternalDocumentsProxyRequestQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetExternalDocumentsProxyRequestQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


