/*
Glean Client API - Platform Preview

# Introduction These are all the APIs used by Glean to implement the Glean client. These are available as platform preview for implementing a custom client to the Glean system.  # Usage guidelines A subset of these endpoints are also in the developer ready section, which is available for public use. The rest of the endpoints are subject to prior agreement with Glean before usage. Please contact support@glean.com if you would like to use an API that is not currently available in the developer ready section. 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gleanclientsdk

import (
	"encoding/json"
)

// checks if the DisplayableListFormat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisplayableListFormat{}

// DisplayableListFormat struct for DisplayableListFormat
type DisplayableListFormat struct {
	// defines how to render this particular displayable list card
	Format *string `json:"format,omitempty"`
}

// NewDisplayableListFormat instantiates a new DisplayableListFormat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisplayableListFormat() *DisplayableListFormat {
	this := DisplayableListFormat{}
	return &this
}

// NewDisplayableListFormatWithDefaults instantiates a new DisplayableListFormat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisplayableListFormatWithDefaults() *DisplayableListFormat {
	this := DisplayableListFormat{}
	return &this
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *DisplayableListFormat) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DisplayableListFormat) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *DisplayableListFormat) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *DisplayableListFormat) SetFormat(v string) {
	o.Format = &v
}

func (o DisplayableListFormat) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisplayableListFormat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	return toSerialize, nil
}

type NullableDisplayableListFormat struct {
	value *DisplayableListFormat
	isSet bool
}

func (v NullableDisplayableListFormat) Get() *DisplayableListFormat {
	return v.value
}

func (v *NullableDisplayableListFormat) Set(val *DisplayableListFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableDisplayableListFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableDisplayableListFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisplayableListFormat(val *DisplayableListFormat) *NullableDisplayableListFormat {
	return &NullableDisplayableListFormat{value: val, isSet: true}
}

func (v NullableDisplayableListFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisplayableListFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


