/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions. 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gleanclientsdk

import (
	"encoding/json"
)

// checks if the CustomFieldData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomFieldData{}

// CustomFieldData struct for CustomFieldData
type CustomFieldData struct {
	// A user-facing label for this field.
	Label string `json:"label"`
	Values []CustomFieldValue `json:"values"`
	// Determines whether the client should display this custom field
	Displayable bool `json:"displayable"`
}

// NewCustomFieldData instantiates a new CustomFieldData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomFieldData(label string, values []CustomFieldValue, displayable bool) *CustomFieldData {
	this := CustomFieldData{}
	this.Label = label
	this.Values = values
	this.Displayable = displayable
	return &this
}

// NewCustomFieldDataWithDefaults instantiates a new CustomFieldData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomFieldDataWithDefaults() *CustomFieldData {
	this := CustomFieldData{}
	var displayable bool = true
	this.Displayable = displayable
	return &this
}

// GetLabel returns the Label field value
func (o *CustomFieldData) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *CustomFieldData) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *CustomFieldData) SetLabel(v string) {
	o.Label = v
}

// GetValues returns the Values field value
func (o *CustomFieldData) GetValues() []CustomFieldValue {
	if o == nil {
		var ret []CustomFieldValue
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *CustomFieldData) GetValuesOk() ([]CustomFieldValue, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *CustomFieldData) SetValues(v []CustomFieldValue) {
	o.Values = v
}

// GetDisplayable returns the Displayable field value
func (o *CustomFieldData) GetDisplayable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Displayable
}

// GetDisplayableOk returns a tuple with the Displayable field value
// and a boolean to check if the value has been set.
func (o *CustomFieldData) GetDisplayableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Displayable, true
}

// SetDisplayable sets field value
func (o *CustomFieldData) SetDisplayable(v bool) {
	o.Displayable = v
}

func (o CustomFieldData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomFieldData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["label"] = o.Label
	toSerialize["values"] = o.Values
	toSerialize["displayable"] = o.Displayable
	return toSerialize, nil
}

type NullableCustomFieldData struct {
	value *CustomFieldData
	isSet bool
}

func (v NullableCustomFieldData) Get() *CustomFieldData {
	return v.value
}

func (v *NullableCustomFieldData) Set(val *CustomFieldData) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomFieldData) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomFieldData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomFieldData(val *CustomFieldData) *NullableCustomFieldData {
	return &NullableCustomFieldData{value: val, isSet: true}
}

func (v NullableCustomFieldData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomFieldData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


