/*
Glean Client API - Platform Preview

# Introduction These are all the APIs used by Glean to implement the Glean client. These are available as platform preview for implementing a custom client to the Glean system.  # Usage guidelines A subset of these endpoints are also in the developer ready section, which is available for public use. The rest of the endpoints are subject to prior agreement with Glean before usage. Please contact support@glean.com if you would like to use an API that is not currently available in the developer ready section. 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gleanclientsdk

import (
	"encoding/json"
)

// checks if the SchemasGrantPermission type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemasGrantPermission{}

// SchemasGrantPermission Describes the grant permission level that a user has for a specific feature
type SchemasGrantPermission struct {
	ScopeType *ScopeType `json:"scopeType,omitempty"`
}

// NewSchemasGrantPermission instantiates a new SchemasGrantPermission object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemasGrantPermission() *SchemasGrantPermission {
	this := SchemasGrantPermission{}
	return &this
}

// NewSchemasGrantPermissionWithDefaults instantiates a new SchemasGrantPermission object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemasGrantPermissionWithDefaults() *SchemasGrantPermission {
	this := SchemasGrantPermission{}
	return &this
}

// GetScopeType returns the ScopeType field value if set, zero value otherwise.
func (o *SchemasGrantPermission) GetScopeType() ScopeType {
	if o == nil || IsNil(o.ScopeType) {
		var ret ScopeType
		return ret
	}
	return *o.ScopeType
}

// GetScopeTypeOk returns a tuple with the ScopeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemasGrantPermission) GetScopeTypeOk() (*ScopeType, bool) {
	if o == nil || IsNil(o.ScopeType) {
		return nil, false
	}
	return o.ScopeType, true
}

// HasScopeType returns a boolean if a field has been set.
func (o *SchemasGrantPermission) HasScopeType() bool {
	if o != nil && !IsNil(o.ScopeType) {
		return true
	}

	return false
}

// SetScopeType gets a reference to the given ScopeType and assigns it to the ScopeType field.
func (o *SchemasGrantPermission) SetScopeType(v ScopeType) {
	o.ScopeType = &v
}

func (o SchemasGrantPermission) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemasGrantPermission) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ScopeType) {
		toSerialize["scopeType"] = o.ScopeType
	}
	return toSerialize, nil
}

type NullableSchemasGrantPermission struct {
	value *SchemasGrantPermission
	isSet bool
}

func (v NullableSchemasGrantPermission) Get() *SchemasGrantPermission {
	return v.value
}

func (v *NullableSchemasGrantPermission) Set(val *SchemasGrantPermission) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemasGrantPermission) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemasGrantPermission) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemasGrantPermission(val *SchemasGrantPermission) *NullableSchemasGrantPermission {
	return &NullableSchemasGrantPermission{value: val, isSet: true}
}

func (v NullableSchemasGrantPermission) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemasGrantPermission) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


