/*
Glean Indexing API

# Introduction In addition to the data sources that Glean has built-in support for, Glean also provides a REST API that enables customers to put arbitrary content in the search index. This is useful, for example, for doing permissions-aware search over content in internal tools that reside on-prem as well as for searching over applications that Glean does not currently support first class. In addition these APIs allow the customer to push organization data (people info, organization structure etc) into Glean.  # Early Access Please note that we are continually evolving the system so these APIs are considered “early access” and are subject to change. 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gleansdk

import (
	"encoding/json"
)

// DatasourceMembershipDefinition describes the membership row of a group. Only one of memberUserId and memberGroupName can be specified.
type DatasourceMembershipDefinition struct {
	// The group for which the membership is specified
	GroupName string `json:"groupName"`
	// If the member is a user, then the email or datasource id for the user
	MemberUserId *string `json:"memberUserId,omitempty"`
	// If the member is a group, then the name of the member group
	MemberGroupName *string `json:"memberGroupName,omitempty"`
}

// NewDatasourceMembershipDefinition instantiates a new DatasourceMembershipDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatasourceMembershipDefinition(groupName string) *DatasourceMembershipDefinition {
	this := DatasourceMembershipDefinition{}
	this.GroupName = groupName
	return &this
}

// NewDatasourceMembershipDefinitionWithDefaults instantiates a new DatasourceMembershipDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatasourceMembershipDefinitionWithDefaults() *DatasourceMembershipDefinition {
	this := DatasourceMembershipDefinition{}
	return &this
}

// GetGroupName returns the GroupName field value
func (o *DatasourceMembershipDefinition) GetGroupName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value
// and a boolean to check if the value has been set.
func (o *DatasourceMembershipDefinition) GetGroupNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupName, true
}

// SetGroupName sets field value
func (o *DatasourceMembershipDefinition) SetGroupName(v string) {
	o.GroupName = v
}

// GetMemberUserId returns the MemberUserId field value if set, zero value otherwise.
func (o *DatasourceMembershipDefinition) GetMemberUserId() string {
	if o == nil || o.MemberUserId == nil {
		var ret string
		return ret
	}
	return *o.MemberUserId
}

// GetMemberUserIdOk returns a tuple with the MemberUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatasourceMembershipDefinition) GetMemberUserIdOk() (*string, bool) {
	if o == nil || o.MemberUserId == nil {
		return nil, false
	}
	return o.MemberUserId, true
}

// HasMemberUserId returns a boolean if a field has been set.
func (o *DatasourceMembershipDefinition) HasMemberUserId() bool {
	if o != nil && o.MemberUserId != nil {
		return true
	}

	return false
}

// SetMemberUserId gets a reference to the given string and assigns it to the MemberUserId field.
func (o *DatasourceMembershipDefinition) SetMemberUserId(v string) {
	o.MemberUserId = &v
}

// GetMemberGroupName returns the MemberGroupName field value if set, zero value otherwise.
func (o *DatasourceMembershipDefinition) GetMemberGroupName() string {
	if o == nil || o.MemberGroupName == nil {
		var ret string
		return ret
	}
	return *o.MemberGroupName
}

// GetMemberGroupNameOk returns a tuple with the MemberGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatasourceMembershipDefinition) GetMemberGroupNameOk() (*string, bool) {
	if o == nil || o.MemberGroupName == nil {
		return nil, false
	}
	return o.MemberGroupName, true
}

// HasMemberGroupName returns a boolean if a field has been set.
func (o *DatasourceMembershipDefinition) HasMemberGroupName() bool {
	if o != nil && o.MemberGroupName != nil {
		return true
	}

	return false
}

// SetMemberGroupName gets a reference to the given string and assigns it to the MemberGroupName field.
func (o *DatasourceMembershipDefinition) SetMemberGroupName(v string) {
	o.MemberGroupName = &v
}

func (o DatasourceMembershipDefinition) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["groupName"] = o.GroupName
	}
	if o.MemberUserId != nil {
		toSerialize["memberUserId"] = o.MemberUserId
	}
	if o.MemberGroupName != nil {
		toSerialize["memberGroupName"] = o.MemberGroupName
	}
	return json.Marshal(toSerialize)
}

type NullableDatasourceMembershipDefinition struct {
	value *DatasourceMembershipDefinition
	isSet bool
}

func (v NullableDatasourceMembershipDefinition) Get() *DatasourceMembershipDefinition {
	return v.value
}

func (v *NullableDatasourceMembershipDefinition) Set(val *DatasourceMembershipDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableDatasourceMembershipDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableDatasourceMembershipDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatasourceMembershipDefinition(val *DatasourceMembershipDefinition) *NullableDatasourceMembershipDefinition {
	return &NullableDatasourceMembershipDefinition{value: val, isSet: true}
}

func (v NullableDatasourceMembershipDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatasourceMembershipDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


