name: linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        go-version: [">=1.19.6", ">=1.20.2"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          go install cloudeng.io/citools/multimod@latest

      - name: Test
        run: multimod --config=.multimod.yaml test

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.3"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          go install cloudeng.io/citools/multimod@latest
          go install golang.org/x/vuln/cmd/govulncheck@latest
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      - name: Lint
        run: multimod --config=.multimod.yaml lint

      - name: Vulnerability
        run: multimod --config=.multimod.yaml govuln
